CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) UNIQUE,
  name VARCHAR(255),
  password_hash CHAR(100),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE = InnoDB;

CREATE TABLE urls (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NULL,
  long_url VARCHAR(2048) NOT NULL,
  url_hash CHAR(64) AS (SHA2 (long_url, 256)) STORED,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY idx_url_hash (url_hash),
  FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL
) ENGINE = InnoDB;

CREATE TABLE slugs (
  code VARCHAR(64) PRIMARY KEY,
  url_id INT NOT NULL,
  user_id INT NULL,
  expires_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (url_id) REFERENCES urls (id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL,
  INDEX (user_id),
  INDEX (expires_at)
) ENGINE = InnoDB;

CREATE TABLE previews (
  id INT AUTO_INCREMENT PRIMARY KEY,
  url_id INT NOT NULL,
  provider ENUM ('og', 'twitter') NOT NULL,
  title VARCHAR(256) NULL,
  description TEXT NULL,
  image_url VARCHAR(2048) NULL,
  twitter_card VARCHAR(128) NULL,
  twitter_domain VARCHAR(256) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (url_id) REFERENCES urls (id) ON DELETE CASCADE,
  UNIQUE KEY (url_id, provider)
) ENGINE = InnoDB;

CREATE TABLE hits (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  slug_code VARCHAR(64) NOT NULL,
  referrer VARCHAR(2048) NULL,
  ip_address VARBINARY(16) NULL,
  user_agent TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (slug_code) REFERENCES slugs (code) ON DELETE CASCADE,
  INDEX (slug_code),
  INDEX (created_at)
) ENGINE = InnoDB;
