# Starts a backend Go server.

services:
  rest:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-rest
    ports:
      - 8080:8080
    volumes:
      - ./services/rest:/service
    environment:
      - PORT=8080

  client:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-client
    ports:
      - 5173:5173
    volumes:
      - ./client:/client
      - /app/node_modules
    depends_on:
      - rest

  client-test:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-client
    command: npm test -- --watch
    volumes:
      - ./client:/client
      - /app/node_modules
    working_dir: /client
    environment:
      - NODE_ENV=test
    depends_on:
      - rest
