# Starts a backend Go server.

services:
  rest:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-rest
    ports:
      - 8080:8080
    volumes:
      - ./services/rest:/service
    environment:
      - PORT=8080
      - REDIS_ADDR=redis:6379
    depends_on:
      - redis

  client:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-client
    ports:
      - 5173:5173
    volumes:
      - ./client:/client
      - /app/node_modules
    depends_on:
      - rest
    environment:
      - VITE_REST_URL=http://localhost:8080

  client-test:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-client
    command: npm test -- --watch
    volumes:
      - ./client:/client
      - /app/node_modules
    working_dir: /client
    environment:
      - NODE_ENV=test
      - VITE_REST_URL=http://rest:8080
    depends_on:
      - rest

  redis:
    image: redis:8.0-rc1-alpine
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

volumes:
  redis-data:
