root = "."
tmp_dir = "tmp"

[build]
cmd = "go run ./cmd/server"
include_ext = ["go"]
log = "air.log"
rerun_delay = 500

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true

[screen]
clear_on_rebuild = true
keep_scroll = true
